a1p1: a1p1.c tictactoe.o tictactoe.h
	gcc -Wall -ansi -pedantic a1p1.c tictactoe.o -o a1p1

test: test.c tictactoe.o tictactoe.h
	gcc -Wall -ansi -pedantic test.c tictactoe.o -o test

tictactoe.o: tictactoe.c tictactoe.h
	gcc -Wall -ansi -pedantic -c tictactoe.c -o tictactoe.o
